[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/api/check-uz/:name"
  to = "/.netlify/functions/check-uz/:name"
  status = 200

[[redirects]]
  from = "/api/check-tg/:name"
  to = "/.netlify/functions/check-tg/:name"
  status = 200

[[redirects]]
  from = "/api/check-ig/:name"
  to = "/.netlify/functions/check-ig/:name"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
